server:
  port: 8080

spring:
  datasource:
    #  数据源基本配置
      username: root
      password: root
      url: jdbc:mysql://47.113.82.122:3306/kxw?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.jdbc.Driver

    
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # 指定sql映射文件位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  # configuration:
    # map-underscore-to-camel-case: true

# 打印SQL
logging:
  level:
    com.tell.mapper : debug
